{application,nodejs,
             [{config_mtime,1730562839},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jason,poolboy,
                             ssl_verify_fun]},
              {description,"Provides an Elixir API for calling Node.js functions.\n"},
              {modules,['Elixir.NodeJS','Elixir.NodeJS.Error',
                        'Elixir.NodeJS.Supervisor','Elixir.NodeJS.Worker']},
              {registered,[]},
              {vsn,"3.1.0"}]}.
