{application,live_svelte,
             [{config_mtime,1730562839},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jason,nodejs,phoenix,
                             phoenix_html,phoenix_live_view]},
              {description,"E2E reactivity for Svelte and LiveView"},
              {modules,['Elixir.LiveSvelte','Elixir.LiveSvelte.Components',
                        'Elixir.LiveSvelte.LiveJson',
                        'Elixir.LiveSvelte.Logger','Elixir.LiveSvelte.SSR',
                        'Elixir.LiveSvelte.SSR.NodeJS',
                        'Elixir.LiveSvelte.SSR.NotConfigured',
                        'Elixir.LiveSvelte.Slots',
                        'Elixir.Mix.Tasks.LiveSvelte.ConfigureEsbuild',
                        'Elixir.Mix.Tasks.LiveSvelte.ConfigurePhoenix',
                        'Elixir.Mix.Tasks.LiveSvelte.InstallNpmDeps',
                        'Elixir.Mix.Tasks.LiveSvelte.Setup']},
              {registered,[]},
              {vsn,"0.14.0"}]}.
